# Generated by Django 2.2.2 on 2020-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
