# Generated by Django 2.2.2 on 2020-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0002_signup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AddField(
            model_name='signup',
            name='fname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='lname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
