# Generated by Django 2.2.2 on 2020-08-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0003_auto_20200819_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='lname',
        ),
    ]
