# Generated by Django 3.0.3 on 2020-11-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_url',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
