# Generated by Django 3.0.3 on 2020-11-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0007_videos_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDetailView',
            fields=[
                ('videos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sendemail.Videos')),
            ],
            bases=('sendemail.videos',),
        ),
    ]
